### ISSUE TITLE
Bug: unable to create a new worktree with the Add command

### ISSUE THREAD

**Issue by Sov3rain** [philstainer/git-worktree#10]
Hey Phil,

Today I sat down and tested the new version you published. Unfortunately I can't create a new worktree, I get this error:

```
---------------- Error Message ----------------

Error: command: 'git -C C:\.../worktree-1 push -u origin'. error: 'Command failed: git -C C:\.../worktree-1 push -u origin
fatal: The upstream branch of your current branch does not match
the name of your current branch.  To push to the upstream branch
on the remote, use

    git push origin HEAD:main

To push to the branch of the same name on the remote, use

    git push origin HEAD

To choose either option permanently, see push.default in 'git help config'.

To avoid automatically configuring an upstream branch when its name
won't match the local branch, see option 'simple' of branch.autoSetupMerge
in 'git help config'.
```

I selected main as my tracking branch, and I've got `gitWorktree.worktree.shouldPushBranchAutomatically` set to true.

**Comment by philstainer** [comment]
That's annoying, looks like it's failing to update upstream, It's working for me, but I think that's down to my git config 🤦‍♂️

Raising an MR now

**Comment by philstainer** [comment]
I'll reopen for now but just pushed some fixes, let me know if working 👍

**Comment by Sov3rain** [comment]
Everything seems to work as expected with your update 👌

**Comment by philstainer** [comment]
Great, thanks for reporting the issue 👍
