### ISSUE TITLE
Error when try to git worktree add using VSCode IDE 

### ISSUE THREAD

**Issue by sasaWriteCode** [philstainer/git-worktree#13]
---------------- Error Message ----------------

Error: Bare repository not found

**Comment by philstainer** [comment]
Your repo needs to be a bare repo for this to work 

Publish your repo on github, run the clone command and it will set it all up for you 

https://github.com/philstainer/git-worktree?tab=readme-ov-file#clone-command

**Comment by philstainer** [comment]
Closing for now, if you still have the issue after using the clone command, feel free to reopen :)
