### ISSUE TITLE
Can't clone repo on another drive

### ISSUE THREAD

**Issue by Sov3rain** [philstainer/git-worktree#4]
Hey, I'm trying to clone a repo on another disk than C:\, and I'm getting this error: 

> ---------------- Error Message ----------------
> 
> Error: EINVAL: invalid argument, mkdir 'C:\D:\Workspaces\my-repo'

The path should just be `D:\Workspaces\my-repo`. Any idea? Thanks!

_Windows 10 @latest
VS Code @latest
Git @2.39.2
Git-Worktree @1.2.1_

EDIT: I can't clone anything from the command palette, it always adds `C:\` at the beginning of the path, even if the path already contains `C:\`, like: `C:\C:\Workspaces\my-repo`

**Comment by philstainer** [comment]
Just tested it on Mac and seems to be working fine, let me just spin up the windows pc

**Comment by philstainer** [comment]
Pushing a change to fix this now 👍

**Comment by Sov3rain** [comment]
Sure it does, thank you for you blazingly fast answer and fix. And thank you for taking the time making this extension, the only other alternative out there for managing git worktrees in VS Code is the paid version of Git Lens. Kuddos to you.

**Comment by philstainer** [comment]
No worries, I'm happy to help and glad you find it useful! Enjoy
